camera:
  ros__parameters:
    camera_name: camera
    serial_no: ''
    usb_port_id: ''
    device_type: ''
    config_file: ''
    unite_imu_method: 0
    json_file_path: ''
    log_level: info
    output: screen
    depth_module.profile: 0,0,0
    enable_depth: true
    rgb_camera.profile: 0,0,0
    rgb_camera.enable_auto_exposure: true
    enable_color: true
    enable_infra1: false
    enable_infra2: false
    infra_rgb: false
    enable_fisheye1: true
    enable_fisheye2: true
    enable_confidence: true
    gyro_fps: 0
    accel_fps: 0
    enable_gyro: false
    enable_accel: false
    enable_pose: true
    pose_fps: 200
    pointcloud.enable: false
    pointcloud.stream_filter: 2
    pointcloud.stream_index_filter: 0
    enable_sync: false
    align_depth.enable: false
    colorizer.enable: false
    clip_distance: -2.
    linear_accel_cov: 0.01
    initial_reset: false
    allow_no_texture_points: false
    pointcloud.ordered_pc: false
    tf_publish_rate: 0.0
    diagnostics_period: 0.0
    decimation_filter.enable: false
    rosbag_filename: ''
    depth_module.exposure.1: 7500
    depth_module.gain.1: 16
    depth_module.exposure.2: 1
    depth_module.gain.2: 16
    depth_module.exposure: 8500
    depth_module.hdr_enabled: false
    depth_module.enable_auto_exposure: true
    hdr_merge.enable: false
    wait_for_device_timeout: -1.
    reconnect_timeout: 6.